Mu 15
Staroz/Cypress_automation_training pull request #13
Opened 2023-05-29 07:23 UTC by Staroz

Please, review this PR and give me your feedback. Thanks.

2023-05-29 13:27 UTC, sphinix27 requested changes
The main change would be to create a new test file for Worskpace tests in UI.

2023-05-29 13:27 UTC, sphinix27 commented on cypress/e2e/testBoards.cy.js
> +describe("Manipulating UI of Trello", function() {
I believe you shouldn't change the description of the test

2023-05-29 13:27 UTC, sphinix27 commented on cypress/e2e/testBoards.cy.js
> +    describe("Create a work space whit UI", function () {
This test should go in another test file, only for Workspace.

2023-05-29 13:27 UTC, sphinix27 commented on cypress/e2e/testBoards.cy.js
> +		it("Create WS", function () {
Use full word for this test: `Create WorkSpace`

2023-05-29 13:27 UTC, sphinix27 commented on cypress/support/commands.js
> +    cy.get('[data-testid="header-create-menu-button"]').dblclick().click();
Is it a bug, or maybe another element is being clicked, you can try the option: `{force: true}`

2023-05-29 13:27 UTC, sphinix27 commented on cypress/support/commands.js
> +function getId(arr, boardName) {
This util functions should be in another file and just be imported here, this file should only contain cypress Commands.

2023-05-29 13:27 UTC, sphinix27 commented on tests/pages/UiHandling.page.js
> +
This changes shouldn't be in this PR, for the moment I'll just ignore them.

2023-06-02 23:14 UTC, Staroz commented
Please, review this commit. Thanks

2023-06-05 15:03 UTC, sphinix27 commented
Looks good, Please resolve issues

2023-06-06 06:59 UTC, merged