Mu 16
Staroz/Cypress_automation_training pull request #14
Opened 2023-06-06 07:44 UTC by Staroz

Please, review this task... Thanks

2023-06-06 11:40 UTC, sphinix27 requested changes

2023-06-06 11:40 UTC, sphinix27 commented on README.md
> +  "listName3": "list 3"
Instead of having only three `listNameX` variables I suggest you implement it this way:
```
"listNames": [
  "list 1",
  "list 2",
  "list 3"
]

// or

"listNames": [
  { "listName": "list 1"},
  { "listName": "list 2"},
  { "listName": "list 3"}
]
```

And when reading you already will have a list to use to create all the lists

2023-06-06 11:40 UTC, sphinix27 commented on cypress/support/apiCommands.js
> +    console.log('Todos los workspaces fueron eliminados.');
If you can change all log messages to English.

2023-06-06 11:40 UTC, sphinix27 commented on cypress/support/apiCommands.js
> +    console.error('Ocurrió un error al eliminar los workspaces:', error);
In the case of an error, you should fail somehow the test

2023-06-06 11:40 UTC, sphinix27 commented on cypress/support/commands.js
> +            if (listNameArray) {
Is this required? I believe the wrong validation is made here.

2023-06-07 05:53 UTC, Staroz commented on cypress/support/apiCommands.js
> +    console.log('Todos los workspaces fueron eliminados.');
Sorry, this file should not be visible in the PR, I was wrong not to add it in the .gitignore file

2023-06-07 05:58 UTC, Staroz commented on cypress/support/apiCommands.js
> +    console.error('Ocurrió un error al eliminar los workspaces:', error);
This file is only for deleting workspaces and test boards, it is not used as a function in Cypress test files.

2023-06-07 06:33 UTC, Staroz commented on README.md
> +  "listName3": "list 3"
Thanks for the suggestion.

2023-06-07 06:39 UTC, Staroz commented on cypress/support/commands.js
> +            if (listNameArray) {
You have Razon, this validation isn't required, I believe the FOR cycle is sufficient.

2023-06-07 06:59 UTC, Staroz commented
Please, review this commit. Thanks

2023-06-07 11:21 UTC, sphinix27 approved these changes
LGTM

2023-06-07 11:21 UTC, sphinix27 commented on .gitignore
> +/apiCommands.js/
Interesting ignore?

2023-06-07 11:21 UTC, sphinix27 commented on cypress/e2e/testBoards.cy.js
> +            cy.wait(1500);
In the future try to wait for the appearance/display of an UI element or the response of a API request.

2023-06-07 11:21 UTC, sphinix27 commented on cypress/fixtures/credentials.json
> +                        ""]
I think it should be like: 
```
"listNameArray": []
```
But let's ignore it for a moment.

2023-06-10 03:05 UTC, merged