Mu 19
Staroz/Cypress_automation_training pull request #17
Opened 2023-06-21 10:15 UTC by Staroz

Check this PR, I've been fixing issues from GitHub Actions and I hope to improve this. thank you.

2023-06-21 10:54 UTC, sphinix27 requested changes
Apply suggested changes and fix PR issues

2023-06-21 10:54 UTC, sphinix27 commented on .vscode/settings.json
> +}
Is this required?

2023-06-21 10:54 UTC, sphinix27 commented on cypress/screenshots/updateCards.cy.js/Test for update information of cards in Trello -- Add description in a card -- after all hook (failed).png
Remove all these png files.

2023-06-21 10:54 UTC, sphinix27 commented on playwright-report/index.html
Better to remove the folder `playwright-report`

2023-06-21 10:54 UTC, sphinix27 commented on tests-examples/demo-todo-app.spec.js
Remove this file

2023-06-21 10:54 UTC, sphinix27 commented on tests/cardsTrello.spec.js
> +const axios = require('axios');
Is this import required?

2023-06-21 10:54 UTC, sphinix27 commented on tests/listsTrello.spec.js
> +const axios = require('axios');
Is this import required?

2023-06-21 10:54 UTC, sphinix27 commented on tests/testTrello.spec.js
>  const axios = require('axios');
Is this import required?

2023-06-22 05:28 UTC, Staroz commented
Hi, I've fixed the issues that you saw in my PR, please, review again this PR.

2023-06-22 10:44 UTC, sphinix27 requested changes
Review how to remove existing files from git. Only that is remaining, everything else looks good.

2023-06-22 10:44 UTC, sphinix27 commented on cypress/screenshots/updateCards.cy.js/Test for update information of cards in Trello -- Add description in a card -- after all hook (failed).png
Still these files are added, they should be removed.

2023-06-22 10:44 UTC, sphinix27 commented on cypress/videos/updateCards.cy.js.mp4
Remove this file

2023-06-22 10:44 UTC, sphinix27 commented on playwright-report/index.html
Remove this file

2023-06-22 10:44 UTC, sphinix27 commented on tests-examples/demo-todo-app.spec.js
Remove this file

2023-06-22 10:44 UTC, sphinix27 commented on tests/updateCards.spec.js
> +const { CardsUi } = require('./pages/cardsUi')
In the future when creating Page Object classes, it is better to just name them like: `CardsPage` or `NavPage`

2023-06-23 06:04 UTC, merged

2023-06-23 06:04 UTC, Staroz commented
Thanks for the observations.