Mu 21
Staroz/Cypress_automation_training pull request #19
Opened 2023-06-27 21:22 UTC by Staroz

Please, Review this PR.

2023-06-27 22:03 UTC, sphinix27 requested changes
You are missing the update of the fields for the credential.json, please submit that.

2023-06-27 22:03 UTC, sphinix27 commented on cypress/support/commands.js
> +    cy.get('select.js-select-board').select(boardName+' (current)');
Try to use curly braces for string format.
Example:
```
`${boardName} (current)`
```

2023-06-27 22:03 UTC, sphinix27 commented on cypress/support/commands.js
> +    cy.get('[class="nch-button nch-button--primary wide js-submit"]').click({force: true});
This kind of selectors are not good, try to use only the minimum classes, not all of them, or find something else that can be used to get the element.

2023-06-28 04:22 UTC, Staroz commented
Please, review PR please.

2023-06-28 10:20 UTC, sphinix27 approved these changes
LGTM

2023-06-28 19:51 UTC, merged