Mu 23
Staroz/Cypress_automation_training pull request #21
Opened 2023-07-05 17:38 UTC by Staroz

Please, review this PR.

2023-07-05 17:47 UTC, sphinix27 requested changes
Make the changes and I'll approve.

2023-07-05 17:47 UTC, sphinix27 commented on cypress/e2e/updateCards.cy.js
> +        it.only("add Checklist", function () {
Remove the only

2023-07-09 10:30 UTC, sphinix27 commented
Looks good but pipeline is failing, locators and timeouts seems to be the issue, please take a look at that.

2023-07-10 09:52 UTC, sphinix27 approved these changes
Overall looks good, just read the comments and try to use those locators as suggested.

2023-07-10 09:52 UTC, sphinix27 commented on cypress/support/commands.js
> +    cy.get('[class=" css-191o3mb"]').click();
This locator can be rewritten as `'.css-191o3mb'`

2023-07-10 09:52 UTC, sphinix27 commented on cypress/support/commands.js
> +    cy.get('[id="id-checklist"]').invoke('val', checklistName);
Id locators are used like: `'#id-checklist'`

2023-07-12 20:14 UTC, Staroz commented
Please, Review it  I had problems with the playwright's new version and the change of locators.

2023-07-12 20:18 UTC, Staroz commented
Because some locators and functionality were chanched In Trello

2023-07-16 07:32 UTC, merged