Mu 08
Staroz/Cypress_automation_training pull request #9
Opened 2023-05-05 05:47 UTC by Staroz

Please review Task 08, integrated cypress tests with Github Actions

![image](https://user-images.githubusercontent.com/124112333/236385121-352ae719-4253-4991-90d7-43217535f04a.png)

2023-05-05 10:48 UTC, sphinix27 requested changes
Currently tests are failing, they should always pass, fix the pipeline.

2023-05-05 10:48 UTC, sphinix27 commented on cypress/fixtures/credentials.json
> +  "boardName": " ",
You should remove this empty strings that just have spaces

2023-05-10 04:26 UTC, Staroz commented
Thanks for the recommendations, and please review the commit: 
"change Trello account get better testing and fix GitHub-Actions",
bugshttps://github.com/Staroz/Cypress_automation_training/pull/9/commits/869aa3c190b4a5435d77bf63958480f284b7b321

2023-05-10 04:36 UTC, sphinix27 approved these changes
LGTM!
3 out of 3 tests passed in a row.

2023-05-10 04:44 UTC, merged